version: '3'
services: 

  authentication-service:
    image: drivehub.azurecr.io/soyateam/authentication-service:develop
    ports:
      - 8083:8080
    env_file:
    - ./env/mongo.env
    - ./env/authentication.env
    - ./env/node.env
    depends_on:
    - mongo

  web-ui: 
    image: drivehub.azurecr.io/soyateam/web-ui:develop
    ports:
    - 80:8080
    depends_on:
    - authentication-service
    - brain-service

  brain-service: 
    image: drivehub.azurecr.io/soyateam/brain-service:develop
    ports:
      - 8080:8080
    depends_on:
    - hierarchy-service
    - task-service
    env_file:
    - ./env/node.env

  task-service: 
    image: drivehub.azurecr.io/soyateam/task-service:develop
    ports: 
    - 8081:8080
    depends_on:
    - mongo
    env_file:
    - ./env/mongo.env
    - ./env/node.env

  hierarchy-service:
    image: drivehub.azurecr.io/soyateam/hierarchy-service:develop
    ports:
    - 8082:8080
    env_file:
    - ./env/node.env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-volume:/data/db


