version: '3'
services: 

  authentication-service:
    image: drivehub.azurecr.io/soyateam/authentication-service:develop
    ports:
      - 3000:8080
    env_file:
    - ./env/mongo.env
    - ./env/authentication.env
    - ./env/node.env
    depends_on:
    - mongo

  web-ui: 
    image: drivehub.azurecr.io/soyateam/web-ui:develop
    ports:
    - 1500:8080
    depends_on:
    - authentication-service
    - brain-service

  brain-service: 
    image: drivehub.azurecr.io/soyateam/brain-service:develop
    ports:
      - 3001:8080
    depends_on:
    - group-service
    - task-service
    env_file:
    - ./env/node.env

  task-service: 
    image: drivehub.azurecr.io/soyateam/task-service:develop
    ports: 
    - 3003:8080
    depends_on:
    - mongo
    env_file:
    - ./env/mongo.env
    - ./env/node.env

  group-service:
    image: drivehub.azurecr.io/soyateam/group-service:develop
    ports:
    - 3004:8080
    env_file:
    - ./env/node.env
    - ./env/mongo.env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"


