version: '3.5'
services:
  web-ui:
    image: drivehub.azurecr.io/soyateam/web-ui:develop
    depends_on:
      - brain-service
      - authentication-service
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  brain-service:
    image: drivehub.azurecr.io/soyateam/brain-service:develop
    ports:
      - '3001:8080'
    env_file:
    - ./env/mongo.env
    - ./env/node.env
    restart: always
    depends_on:
      - group-service
      - task-service
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  task-service:
    image: drivehub.azurecr.io/soyateam/task-service:develop
    ports:
      - '3002:8080'
    env_file:
    - ./env/mongo.env
    - ./env/node.env
    restart: always
    depends_on:
      - mongo
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  group-service:
    image: drivehub.azurecr.io/soyateam/group-service:develop
    ports:
      - '3003:8080'
    env_file:
    - ./env/mongo.env
    - ./env/node.env
    restart: always
    depends_on:
      - mongo
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  authentication-service:
    image: drivehub.azurecr.io/soyateam/authentication-service:develop
    ports:
      - '3000:8080'
    env_file:
    - ./env/mongo.env
    - ./env/authentication.env
    - ./env/node.env
    restart: always
    depends_on:
      - mongo
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        mode: ingress
    depends_on:
      - brain-service
      - group-service
      - task-service
      - authentication-service
      - web-ui
    deploy:
      placement:
        constraints: [node.role == manager]